
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

PACKAGE VGA_SETTINGS is

----HORIZONTAL SETTING----
CONSTANT H_TOTAL : NATURAL := 800;
CONSTANT H_PULSE : NATURAL := 96;
CONSTANT H_BACK_PORCH : NATURAL := 48;
CONSTANT H_ACTIVE : NATURAL := 640;
CONSTANT H_FRONT_PORCH : NATURAL := 16;
CONSTANT H_ON_DISPLAY : NATURAL := H_PULSE + H_BACK_PORCH;

CONSTANT H_OFF_DISPLAY  : NATURAL := H_ON_DISPLAY + H_ACTIVE;
CONSTANT H_COUNT_WIDTH : NATURAL := 11;

----VERTICAL---
CONSTANT V_TOTAL : NATURAL := 525;
CONSTANT V_PULSE : NATURAL := 2;
CONSTANT V_BACK_PORCH : NATURAL := 31;
CONSTANT V_ACTIVE : NATURAL := 480;
CONSTANT V_FRONT_PORCH : NATURAL := 11;
CONSTANT V_ON_DISPLAY : NATURAL := V_PULSE + V_BACK_PORCH;

CONSTANT V_OFF_DISPLAY  : NATURAL := V_ON_DISPLAY + V_ACTIVE;
CONSTANT V_COUNT_WIDTH : NATURAL := 11;


-----VGA PORT RGB----
CONSTANT RED_WIDTH : NATURAL := 4;
CONSTANT GREEN_WIDTH : NATURAL := 4;
CONSTANT BLUE_WIDTH : NATURAL := 4;

----HORIZONTAL SETTING----
--CONSTANT H_PERIOD : INTEGER := 800;
--CONSTANT H_PULSE : INTEGER := 96;
--CONSTANT H_BACK_PORCH : INTEGER := 48;
--CONSTANT H_ACTIVE : INTEGER := 640;
--CONSTANT H_FRONT_PORCH : INTEGER := 16;
--CONSTANT H_ON_DISPLAY : INTEGER := H_PULSE + H_BACK_PORCH;

--CONSTANT H_OFF_DISPLAY  : INTEGER := H_ON_DISPLAY + H_ACTIVE;
--CONSTANT H_COUNT_WIDTH : INTEGER := 11;

------VERTICAL---
--CONSTANT V_PERIOD : INTEGER := 525;
--CONSTANT V_PULSE : INTEGER := 2;
--CONSTANT V_BACK_PORCH : INTEGER := 33;
--CONSTANT V_ACTIVE : INTEGER := 480;
--CONSTANT V_FRONT_PORCH : INTEGER := 10;
--CONSTANT V_ON_DISPLAY : INTEGER := V_PULSE + V_BACK_PORCH;

--CONSTANT V_OFF_DISPLAY  : INTEGER := V_ON_DISPLAY + V_ACTIVE;
--CONSTANT V_COUNT_WIDTH : INTEGER := 11;


-------VGA PORT RGB----
--CONSTANT RED_WIDTH : INTEGER := 4;
--CONSTANT GREEN_WIDTH : INTEGER := 4;
--CONSTANT BLUE_WIDTH : INTEGER := 4;



end VGA_SETTINGS;

PACKAGE BODY  VGA_SETTINGS is
end;
